grafana:
  enabled: true
  namespaceOverride: ""

  dashboardsConfigMaps:
    enabled: true

  additionalDataSources:
    enabled: true
    dataSources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated.monitoring.svc:9090
        access: proxy
        isDefault: true

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: 'my-folder'
        type: 'file'
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
